apiVersion: apps/v1
kind: Deployment
metadata:
  name: c22
spec:
  replicas: 1
  selector:
    matchLabels:
      app: c22
  template:
    metadata:
      labels:
        app: c22
    spec:
      containers:
      - image: okteto.dev/c22:latest
        name: c22
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "be17af13-4027-45ed-a55b-1e5e9c94b0fe"
        - name: Vless_Path
          value: "/vlc22"
        - name: Vmess_UUID
          value: "be17af13-4027-45ed-a55b-1e5e9c94b0fe"
        - name: Vmess_Path
          value: "/vmc22"
        - name: Share_Path
          value: "/v2link"
